server:
  port: 8080
  servlet:
    context-path: /movieTheaterManagement

spring:
  datasource:
    url: jdbc:postgresql://db.zpjvpfkwbcnszfzdwynf.supabase.co:5432/postgres
    username: postgres
    password: 3kSE347@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
