
server:
  port: 8080
  servlet:
    context-path: /api/theater-mgnt

spring:
  application:
      name: theater-mgnt
  datasource:
    url: jdbc:postgresql://localhost:5432/theaterdb
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  signerKey: "+PAV/uNVIsN2N1peTkAViUZSSc+t8/wOZQDw8M2+HxBD/2dFy9segSiMPHBr+q97"
  refreshable-duration: 36000
  valid-duration: 3600

