server:
  port: 8080
  servlet:
    context-path: /theater-mgnt

spring:
  application:
    name: theater-mgnt
#  datasource:
#    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres
#    username: postgres.zpjvpfkwbcnszfzdwynf
#    password: 3kSE347@123
#    driver-class-name: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/theater-mgnt
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  signerKey: "+PAV/uNVIsN2N1peTkAViUZSSc+t8/wOZQDw8M2+HxBD/2dFy9segSiMPHBr+q97"